llms:
  embedding:
    style: openai-compatible
    endpoint: http://192.168.0.25:1234/v1
    model_name: text-embedding-embeddinggemma-300m-qat
    apiKey: "sk-lm-rCKFBsk5:XVrIaU7kCFs0KpqSQkUF"
    default_dims: 768
  query_expander:
    style: openai-compatible
    endpoint: http://192.168.0.25:1234/v1
    model_name: qwen3-1.7b
    apiKey: "sk-lm-rCKFBsk5:XVrIaU7kCFs0KpqSQkUF"
  reranking:
    style: openai-compatible
    endpoint: http://192.168.0.25:1234/v1
    name: qwen3-reranker-0.6b      
    apiKey: "sk-lm-rCKFBsk5:XVrIaU7kCFs0KpqSQkUF"
  structured_ocr:
    style: openai-compatible
    endpoint: https://openrouter.ai/api/v1
    model_name: openai/gpt-5-mini
    apiKey: "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"
    thinking: on
  nano:
    style: openai-compatible
    endpoint: http://192.168.0.25:1234/v1
    model_name: qwen3-1.7b
    apiKey: "sk-lm-rCKFBsk5:XVrIaU7kCFs0KpqSQkUF"
    thinking: off
  capable:
    style: openai-compatible
    endpoint: http://192.168.0.25:1234/v1
    model_name: qwen3-1.7b
    apiKey: "sk-lm-rCKFBsk5:XVrIaU7kCFs0KpqSQkUF"
    thinking: medium